=== wckhg89/MyProject/WebProgramming/Exercise_XML/Ex3/bulletin.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="board">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="boardname" maxOccurs="1" />
				<xs:element name="articles" type="article_type"
					maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="article_type">
		<xs:sequence>
			<xs:element name="title" maxOccurs="1" />
			<xs:element name="message" maxOccurs="1" />
			<xs:element name="writerID" maxOccurs="1" />
			<xs:element name="writerName" maxOccurs="1" />
			<xs:element name="reply" type="reply_type" maxOccurs="unbounded"
				minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="reply_type">
		<xs:sequence>
			<xs:element name="message" maxOccurs="1" />
			<xs:element name="writerID" maxOccurs="1" />
			<xs:element name="writerName" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== wckhg89/MyProject/WebProgramming/Exercise_XML/Ex3/bulletinForXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<board xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="bulletin.xsd">
	<boardname>자유게시판</boardname>
	<articles>
		<title>짱짱맨</title>
		<message>완전짱짱맨이야</message>
		<writerID>짱짱보이</writerID>
		<writerName>유아인</writerName>
		<reply>
			<message>우왕</message>
			<writerID>짱짱걸</writerID>
			<writerName>김태희</writerName>
		</reply>
	</articles>
</board>
