=== wckhg89/MyProject/WebProgramming/Exercise_XML/Ex1/newspaper.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="newspaper">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="article" type ="article_type" maxOccurs="unbounded"
					minOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>


	<xs:complexType name="article_type">
		<xs:sequence>
			<xs:element name="headline" type="xs:string" />
			<xs:element name="byline" type="xs:string" />
			<xs:element name="lead" type="xs:string" />
			<xs:element name="body" type="xs:string" />
			<xs:element name="notes" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="author" type="xs:string" use="required" />
		<xs:attribute name="editor" type="xs:string" use="optional" />
		<xs:attribute name="date" type="xs:string" use="optional" />
		<xs:attribute name="edition" type="xs:string" use="optional" />
	</xs:complexType>

</xs:schema>

=== wckhg89/MyProject/WebProgramming/Exercise_XML/Ex1/newspaper.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<newspaper xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="newspaper.xsd">
	<article author="honggukang">
		<headline>인천아시안게임</headline>
		<byline>인천</byline>
		<lead>아시안</lead>
		<body>게임</body>
		<notes>짱짱맨</notes>
	</article>
	
	<article author="hongpalkang">
		<headline>아시안컴</headline>
		<byline>아시안</byline>
		<lead>컵</lead>
		<body>우승</body>
		<notes>짱짱맨</notes>
	</article>
	
</newspaper>
